"""
models.py — all 7 SQLAlchemy ORM models (database tables).

Table summary:
  users           — all five user roles, with optional institution link
  institutions    — first-class entity so we can query across batches cleanly
  batches         — a cohort of students under an institution
  batch_trainers  — many-to-many junction (a batch can have multiple trainers)
  batch_students  — many-to-many junction (students enrolled in a batch)
  batch_invites   — single-use tokenised invite links generated by trainers
  sessions        — a specific class session within a batch
  attendance      — a student's attendance record for one session

Design decisions:
  - institutions is a separate table (not a string column on users) so summary
    queries work cleanly without string matching.
  - batch_trainers uses a composite PK + UniqueConstraint to prevent duplicate
    trainer assignments while still allowing the association to be queried.
  - batch_invites uses secrets.token_urlsafe(32) — URL-safe random tokens with
    a 7-day expiry.  Once used, `used=True` is set so the token can't be reused.
"""
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, ForeignKey,
    Integer, String, Time, UniqueConstraint,
)
from sqlalchemy.orm import relationship

from src.db.database import Base


class Institution(Base):
    __tablename__ = "institutions"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False, unique=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    users = relationship("User", back_populates="institution")
    batches = relationship("Batch", back_populates="institution")


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    email = Column(String, nullable=False, unique=True, index=True)
    hashed_password = Column(String, nullable=False)
    # role is an ENUM column — the DB enforces valid values
    role = Column(
        Enum(
            "student", "trainer", "institution",
            "programme_manager", "monitoring_officer",
            name="user_role",
        ),
        nullable=False,
    )
    # nullable FK — students and trainers have an optional institution link
    institution_id = Column(Integer, ForeignKey("institutions.id"), nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    institution = relationship("Institution", back_populates="users")
    trainer_batches = relationship("BatchTrainer", back_populates="trainer")
    student_batches = relationship("BatchStudent", back_populates="student")
    invites_created = relationship("BatchInvite", back_populates="creator")
    sessions_created = relationship("Session", back_populates="trainer")
    attendance_records = relationship("Attendance", back_populates="student")


class Batch(Base):
    __tablename__ = "batches"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    institution_id = Column(Integer, ForeignKey("institutions.id"), nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    institution = relationship("Institution", back_populates="batches")
    trainers = relationship("BatchTrainer", back_populates="batch")
    students = relationship("BatchStudent", back_populates="batch")
    invites = relationship("BatchInvite", back_populates="batch")
    sessions = relationship("Session", back_populates="batch")


class BatchTrainer(Base):
    """
    Many-to-many: a batch can have multiple trainers; a trainer can run multiple batches.
    Composite PK prevents duplicates without a separate unique index.
    """
    __tablename__ = "batch_trainers"
    __table_args__ = (UniqueConstraint("batch_id", "trainer_id"),)

    batch_id = Column(Integer, ForeignKey("batches.id"), primary_key=True)
    trainer_id = Column(Integer, ForeignKey("users.id"), primary_key=True)

    batch = relationship("Batch", back_populates="trainers")
    trainer = relationship("User", back_populates="trainer_batches")


class BatchStudent(Base):
    """Many-to-many: students enrolled in a batch."""
    __tablename__ = "batch_students"
    __table_args__ = (UniqueConstraint("batch_id", "student_id"),)

    batch_id = Column(Integer, ForeignKey("batches.id"), primary_key=True)
    student_id = Column(Integer, ForeignKey("users.id"), primary_key=True)

    batch = relationship("Batch", back_populates="students")
    student = relationship("User", back_populates="student_batches")


class BatchInvite(Base):
    """
    Single-use invite token generated by a trainer.
    URL-safe 32-byte random token, 7-day expiry.
    After a student joins, `used` is set to True.
    """
    __tablename__ = "batch_invites"

    id = Column(Integer, primary_key=True, index=True)
    batch_id = Column(Integer, ForeignKey("batches.id"), nullable=False)
    token = Column(String, nullable=False, unique=True, index=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    expires_at = Column(DateTime, nullable=False)
    used = Column(Boolean, default=False, nullable=False)

    batch = relationship("Batch", back_populates="invites")
    creator = relationship("User", back_populates="invites_created")


class Session(Base):
    """A scheduled class session within a batch."""
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    batch_id = Column(Integer, ForeignKey("batches.id"), nullable=False)
    trainer_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    date = Column(String, nullable=False)          # stored as ISO date string YYYY-MM-DD
    start_time = Column(String, nullable=False)    # stored as HH:MM:SS
    end_time = Column(String, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    batch = relationship("Batch", back_populates="sessions")
    trainer = relationship("User", back_populates="sessions_created")
    attendance_records = relationship("Attendance", back_populates="session")


class Attendance(Base):
    """A student's attendance record for a single session."""
    __tablename__ = "attendance"
    __table_args__ = (UniqueConstraint("session_id", "student_id"),)

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False)
    student_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    status = Column(
        Enum("present", "absent", "late", name="attendance_status"),
        nullable=False,
    )
    marked_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    session = relationship("Session", back_populates="attendance_records")
    student = relationship("User", back_populates="attendance_records")